apiVersion: v1
kind: Service
metadata:
  name: url-shortner-service
spec:
  selector:
    app: url-shortner
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: ClusterIP # Change to LoadBalancer if using a cloud provider
